"""
Breed metadata seeded on startup.
Names match the EXACT class names from the trained Stanford Dogs model.
"""
from sqlalchemy.orm import Session
from app.db.models import BreedMetadata

_BREEDS = [
    # ── Toy / companion ───────────────────────────────────────────────────────
    {"name": "Chihuahua", "description": "The world's smallest breed packs an enormous personality into a tiny frame. Fiercely loyal, alert, and surprisingly bold.", "temperament": "Alert, Courageous, Loyal, Lively", "size": "Small", "origin": "Mexico", "lifespan": "14–16 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "Chihuahuas have the largest brain-to-body-size ratio of any dog breed."},
    {"name": "Japanese Spaniel", "description": "Elegant and cat-like, the Japanese Chin was bred exclusively as a companion for Japanese nobility. They walk with a distinctive rolling gait.", "temperament": "Loving, Loyal, Intelligent, Cat-Like", "size": "Small", "origin": "Japan", "lifespan": "10–12 years", "energy_level": "Low", "shedding": "Medium", "fun_fact": "Japanese Chins were so prized by Japanese emperors they were sometimes given as diplomatic gifts to foreign royalty."},
    {"name": "Maltese Dog", "description": "One of the oldest toy breeds, Maltese have been companions to aristocracy for over 2,000 years. Their flowing white coat is their signature.", "temperament": "Gentle, Affectionate, Fearless, Lively", "size": "Small", "origin": "Malta", "lifespan": "12–15 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "Ancient Greeks built tombs for their Maltese dogs. Aristotle called them 'perfectly proportioned' specimens."},
    {"name": "Pekinese", "description": "Regal and independent, the Pekingese was the sacred dog of Chinese emperors. They carry themselves with an air of self-importance.", "temperament": "Loyal, Regal, Stubborn, Affectionate", "size": "Small", "origin": "China", "lifespan": "12–14 years", "energy_level": "Low", "shedding": "Heavy", "fun_fact": "Stealing a Pekingese from the Chinese Imperial Palace was punishable by death. They were hidden in the sleeves of royalty."},
    {"name": "Shih-Tzu", "description": "Bred exclusively as a palace companion in ancient China, the Shih Tzu is happy, outgoing, and loves nothing more than sitting in a warm lap.", "temperament": "Affectionate, Outgoing, Spunky, Friendly", "size": "Small", "origin": "China / Tibet", "lifespan": "10–18 years", "energy_level": "Low", "shedding": "Low", "fun_fact": "DNA analysis places the Shih Tzu among the most ancient breeds, genetically closest to wolves of any living dog breed."},
    {"name": "Blenheim Spaniel", "description": "The Blenheim is a chestnut-and-white variety of the Cavalier King Charles Spaniel, named after Blenheim Palace where the Duke of Marlborough bred them.", "temperament": "Gentle, Affectionate, Graceful, Playful", "size": "Small", "origin": "England", "lifespan": "12–15 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "The distinctive red spot on the forehead of Blenheim Spaniels is called the 'Blenheim spot' — legend says the Duchess pressed her thumb there while awaiting news of the Battle of Blenheim."},
    {"name": "Papillon", "description": "Named for their butterfly-like ears, Papillons are one of the oldest and most agile toy breeds. They excel at agility despite their small size.", "temperament": "Alert, Friendly, Energetic, Intelligent", "size": "Small", "origin": "France / Belgium", "lifespan": "14–16 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Papillon means 'butterfly' in French. Marie Antoinette reportedly carried her Papillon to the guillotine."},
    {"name": "Toy Terrier", "description": "The English Toy Terrier is a sleek, elegant breed descended from working ratting terriers. They are keen, alert, and devoted companions.", "temperament": "Alert, Devoted, Keen, Discerning", "size": "Small", "origin": "England", "lifespan": "12–13 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Toy Terriers were once used in rat-killing competitions. A single dog could kill dozens of rats in minutes."},

    # ── Hounds ────────────────────────────────────────────────────────────────
    {"name": "Rhodesian Ridgeback", "description": "Bred by the Khoikhoi people of southern Africa, the Ridgeback has a distinctive ridge of hair growing against the coat. Originally used to bay lions.", "temperament": "Loyal, Strong-Willed, Sensitive, Dignified", "size": "Large", "origin": "Zimbabwe / South Africa", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Rhodesian Ridgebacks don't attack lions — they harass and hold them at bay, barking loudly until hunters arrive."},
    {"name": "Afghan Hound", "description": "Aristocratic and aloof, the Afghan Hound is one of the oldest sighthound breeds. Their silky flowing coat adapted to the harsh Afghan mountains.", "temperament": "Aloof, Clownish, Independent, Happy", "size": "Large", "origin": "Afghanistan", "lifespan": "12–18 years", "energy_level": "High", "shedding": "Low", "fun_fact": "The Afghan Hound was the first dog to be cloned — South Korean scientists cloned an Afghan named Snuppy in 2005."},
    {"name": "Basset", "description": "Calm and friendly with a superb nose, the Basset Hound was bred in France for slow, deliberate rabbit hunting. Their long ears sweep scent toward the nose.", "temperament": "Patient, Charming, Low-Key, Stubborn", "size": "Medium", "origin": "France", "lifespan": "12–13 years", "energy_level": "Low", "shedding": "Medium", "fun_fact": "Bassets have the second-keenest sense of smell of any dog breed after the Bloodhound — with around 220 million scent receptors."},
    {"name": "Beagle", "description": "Merry and curious, Beagles are compact scent hounds with exceptional noses. They are sturdy, friendly, and love the company of other dogs and people.", "temperament": "Merry, Curious, Friendly, Determined", "size": "Small", "origin": "England", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Beagles are the most common breed used in laboratory research due to their docile temperament and manageable size."},
    {"name": "Bloodhound", "description": "The Bloodhound has the most powerful nose of any animal on Earth. Their scent-tracking ability is so reliable that trails they identify are admissible in court.", "temperament": "Gentle, Stubborn, Affectionate, Inquisitive", "size": "Large", "origin": "Belgium / England", "lifespan": "10–12 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "A Bloodhound can follow a scent trail over 130 miles long and track a scent that is two weeks old."},
    {"name": "Bluetick", "description": "An American breed developed from French hounds, the Bluetick Coonhound is a tenacious night hunter prized for its cold-nose ability to track old scent trails.", "temperament": "Friendly, Intelligent, Active, Tenacious", "size": "Large", "origin": "United States", "lifespan": "11–12 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Bluetick Coonhounds are the official state dog of Tennessee. Their distinctive baying call can be heard from miles away."},
    {"name": "Black-And-Tan Coonhound", "description": "Bred for hunting raccoon and bear, the Black and Tan Coonhound is a determined trail dog. At home they are calm, gentle, and sociable.", "temperament": "Easygoing, Trusting, Gentle, Adaptable", "size": "Large", "origin": "United States", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Black and Tan Coonhounds are among America's oldest native breeds, descended from the Talbot Hound brought to the US in the 1600s."},
    {"name": "Walker Hound", "description": "The Treeing Walker Coonhound is a fast, competitive hunter descended from English Foxhounds. They have exceptional treeing ability and a clear bugling voice.", "temperament": "Smart, Brave, Sensible, Confident", "size": "Large", "origin": "United States", "lifespan": "12–13 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Walker Hounds are so fast they are nicknamed 'the People's Choice' in competitive coon hunting. They can clear terrain at remarkable speed."},
    {"name": "English Foxhound", "description": "Bred over centuries for the English fox hunt, the English Foxhound is a pack dog through and through — sociable, energetic, and with extraordinary stamina.", "temperament": "Sociable, Gentle, Active, Tolerant", "size": "Large", "origin": "England", "lifespan": "10–13 years", "energy_level": "High", "shedding": "Low", "fun_fact": "English Foxhounds have been selectively bred for over 250 years. The English Masters of Foxhounds Association maintains studbooks dating to 1800."},
    {"name": "Redbone", "description": "A distinctly American breed, the Redbone Coonhound is a passionate hunter with a rich red coat and a melodious voice. They are gentle and devoted companions.", "temperament": "Eager, Affectionate, Even-Tempered, Trainable", "size": "Large", "origin": "United States", "lifespan": "11–12 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Redbones are featured in the novel 'Where the Red Fern Grows.' Their deep red coats come from early Irish Foxhound ancestry."},
    {"name": "Borzoi", "description": "Aristocratic and quiet, Borzois are Russian sighthounds bred by czars for wolf hunting on the vast steppes. They are gentle and affectionate but fiercely independent.", "temperament": "Gentle, Athletic, Quiet, Independent", "size": "Large", "origin": "Russia", "lifespan": "9–14 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "Borzois can reach speeds of 58 km/h — among the fastest dog breeds. They hunt by sight rather than scent."},
    {"name": "Irish Wolfhound", "description": "The tallest of all dog breeds, Irish Wolfhounds are gentle giants. Despite their imposing size, they are calm, dignified, and sensitive.", "temperament": "Gentle, Calm, Dignified, Courageous", "size": "Giant", "origin": "Ireland", "lifespan": "6–10 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "Irish Wolfhounds were historically used to hunt wolves in Ireland — a single dog could bring down a full-grown wolf. They nearly went extinct in the 1800s."},
    {"name": "Italian Greyhound", "description": "The smallest of the sighthound breeds, Italian Greyhounds are elegant and affectionate. They bond intensely with their owners and hate cold weather.", "temperament": "Sensitive, Alert, Playful, Mischievous", "size": "Small", "origin": "Italy", "lifespan": "14–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Italian Greyhounds have been prized as companions since ancient Egypt. Mummies of small greyhound-type dogs have been found in Egyptian tombs."},
    {"name": "Whippet", "description": "Often called 'the poor man's racehorse,' Whippets are the fastest dogs of their weight, reaching 56 km/h. At home they are calm, affectionate couch dogs.", "temperament": "Quiet, Affectionate, Gentle, Alert", "size": "Medium", "origin": "England", "lifespan": "12–15 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "Whippets were bred by coal miners in northern England for rabbit coursing and racing. They can accelerate from 0 to 56 km/h in seconds."},
    {"name": "Ibizan Hound", "description": "One of the oldest breeds in recorded history, the Ibizan Hound has appeared in ancient Egyptian art. They are elegant hunters with large, upright ears.", "temperament": "Active, Alert, Engaging, Stubborn", "size": "Large", "origin": "Balearic Islands, Spain", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Ibizan Hounds look almost identical to the Egyptian god Anubis and appear in tomb paintings over 5,000 years old."},
    {"name": "Norwegian Elkhound", "description": "A bold and energetic Spitz breed from ancient Scandinavia, the Norwegian Elkhound hunted elk, bear, and moose. They are loyal and playful with family.", "temperament": "Bold, Energetic, Loyal, Playful", "size": "Medium", "origin": "Norway", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Norwegian Elkhounds are one of the oldest breeds in the world — skeletons of similar dogs have been found in Norway dating to 4,000–5,000 BC."},
    {"name": "Otterhound", "description": "One of the rarest breeds in the world, Otterhounds were bred in England to hunt otters. They have a rough double coat, webbed feet, and an extraordinary nose.", "temperament": "Boisterous, Amiable, Even-Tempered, Friendly", "size": "Large", "origin": "England", "lifespan": "10–13 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "There are fewer than 800 Otterhounds in the world — they are rarer than Giant Pandas. Otter hunting was banned in Britain in 1978."},
    {"name": "Saluki", "description": "Possibly the world's oldest domesticated dog, the Saluki appears in ancient Sumerian art from 7,000 BC. They are elegant, swift, and fiercely loyal to their chosen person.", "temperament": "Gentle, Reserved, Intelligent, Aloof", "size": "Large", "origin": "Middle East", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Salukis were considered a gift from Allah in Islamic culture and the only dog permitted inside Bedouin tents. They were mummified like pharaohs."},
    {"name": "Scottish Deerhound", "description": "The royal dog of Scotland, the Deerhound is a large rough-coated sighthound that hunted red deer on the Scottish Highlands. Dignified and gentle.", "temperament": "Gentle, Dignified, Polite, Friendly", "size": "Large", "origin": "Scotland", "lifespan": "8–11 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "Sir Walter Scott called the Scottish Deerhound 'the most perfect creature of Heaven.' The breed nearly went extinct after the Highland Clearances."},

    # ── Terriers ──────────────────────────────────────────────────────────────
    {"name": "Weimaraner", "description": "Sleek and aristocratic, Weimaraners were bred by German royalty for big-game hunting. They bond intensely with owners and dislike being left alone.", "temperament": "Friendly, Fearless, Alert, Obedient", "size": "Large", "origin": "Germany", "lifespan": "11–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "William Wegman's famous photo series featured Weimaraners in costumes for over 50 years. Their silvery coat earned them the nickname 'Grey Ghost.'"},
    {"name": "Staffordshire Bullterrier", "description": "Fearless and tenacious but affectionate with family, the Staffordshire Bull Terrier is known as the 'nanny dog' for its love of children.", "temperament": "Bold, Fearless, Affectionate, Reliable", "size": "Medium", "origin": "England", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "The Staffordshire Bull Terrier is one of only two breeds that the UK Kennel Club specifically mentions being good with children in its breed standard."},
    {"name": "American Staffordshire Terrier", "description": "Confident and good-natured, the AmStaff is a muscular but people-oriented breed. When well-socialised, they are gentle and playful family dogs.", "temperament": "Confident, Smart, Good-Natured, Loyal", "size": "Medium", "origin": "United States", "lifespan": "12–16 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Sergeant Stubby, a decorated WWI hero dog, was an American Staffordshire Terrier mix. He captured a German spy and was promoted to sergeant."},
    {"name": "Bedlington Terrier", "description": "Looking like a small lamb, the Bedlington Terrier is a graceful but tenacious hunter. They combine elegance with spirit and love to run at full speed.", "temperament": "Spirited, Loyal, Mild-Mannered, Energetic", "size": "Medium", "origin": "England", "lifespan": "14–16 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Despite their lamb-like appearance, Bedlington Terriers were originally used to hunt rats, rabbits, and badgers in Northumberland coal mines."},
    {"name": "Border Terrier", "description": "Tough and workmanlike, the Border Terrier was bred to follow horses and hunt foxes along the Scottish border. They are affectionate and highly adaptable.", "temperament": "Affectionate, Intelligent, Alert, Obedient", "size": "Small", "origin": "Scotland / England", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Border Terriers have an otter-shaped head — their skull is broad and flat, different from other terriers, allowing them to squeeze through narrow underground passages."},
    {"name": "Kerry Blue Terrier", "description": "The national dog of Ireland, the Kerry Blue is a versatile working terrier that herded livestock, hunted, and guarded farms. Their blue-grey coat is distinctive.", "temperament": "Spirited, Alert, Adaptable, Loyal", "size": "Medium", "origin": "Ireland", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Kerry Blue Terriers are born black — their coat gradually changes to the characteristic blue-grey by 18 months of age."},
    {"name": "Irish Terrier", "description": "One of the oldest terrier breeds, the Irish Terrier is known as the 'daredevil' of the terrier world — fiery, loyal, and fearless.", "temperament": "Daring, Loyal, Spirited, Protective", "size": "Medium", "origin": "Ireland", "lifespan": "13–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Irish Terriers served as messenger and sentinel dogs in WWI, earning them the nickname 'The Dare-Devils' from British soldiers."},
    {"name": "Norfolk Terrier", "description": "The smallest of the working terriers, the Norfolk is a 'big dog in a small package' — fearless, loyal, and fond of digging.", "temperament": "Fearless, Cheerful, Sociable, Adaptable", "size": "Small", "origin": "England", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Norfolk and Norwich Terriers were the same breed until 1964 when the Kennel Club separated them — the only difference is ear shape (folded vs. prick)."},
    {"name": "Norwich Terrier", "description": "Compact and energetic, the Norwich Terrier is one of the smallest working terriers with prick ears and an outgoing, fearless personality.", "temperament": "Affectionate, Lively, Happy, Compact", "size": "Small", "origin": "England", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Norwich Terriers were originally called 'Trumpington Terriers' — named after a street in Cambridge where they were popular with university students."},
    {"name": "Yorkshire Terrier", "description": "Tenacious and feisty despite their tiny size, Yorkies have big personalities and a beautiful silky coat. Originally bred to catch rats in clothing mills.", "temperament": "Bold, Confident, Courageous, Affectionate", "size": "Small", "origin": "England", "lifespan": "13–16 years", "energy_level": "High", "shedding": "Low", "fun_fact": "The smallest Yorkshire Terrier on record weighed just 113 grams — the size of a tennis ball. Yorkies were the most popular breed in the US in the mid-2000s."},
    {"name": "Wire-Haired Fox Terrier", "description": "The quintessential terrier, the Wire Fox Terrier is bold, energetic, and always ready for adventure. They dominated early dog shows in the 19th century.", "temperament": "Alert, Confident, Friendly, Amusing", "size": "Small", "origin": "England", "lifespan": "13–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Wire Fox Terriers have won Best in Show at Westminster more than any other breed — 14 times. Asta from 'The Thin Man' movies was a Wire Fox Terrier."},
    {"name": "Lakeland Terrier", "description": "Originally used to protect sheep from foxes in England's Lake District, the Lakeland Terrier is confident, workmanlike, and friendly.", "temperament": "Confident, Bold, Friendly, Independent", "size": "Small", "origin": "England", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Lakeland Terriers can squeeze through any gap their head fits through. They were bred to pursue foxes underground in rocky terrain."},
    {"name": "Sealyham Terrier", "description": "One of the rarest terrier breeds, the Sealyham was bred in Wales as an all-purpose hunter. They are more laid-back than most terriers.", "temperament": "Calm, Alert, Sense of Humour, Independent", "size": "Small", "origin": "Wales", "lifespan": "12–14 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "Sealyham Terriers have been owned by Princess Margaret, Cary Grant, Alfred Hitchcock, and Elizabeth Taylor. They nearly went extinct in the 1990s."},
    {"name": "Airedale", "description": "The 'King of Terriers' is the largest terrier breed, versatile enough to hunt large game, serve in war, and act as a loyal family companion.", "temperament": "Courageous, Intelligent, Friendly, Confident", "size": "Medium", "origin": "England", "lifespan": "11–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Airedales served as messengers, sentry dogs, and ambulance dogs in WWI. One named Jack delivered messages through enemy fire and earned the Victoria Cross posthumously."},
    {"name": "Cairn", "description": "The Cairn Terrier is one of Scotland's oldest working terriers, bred to hunt prey among the rocky cairns of the Scottish Highlands.", "temperament": "Alert, Cheerful, Fearless, Loyal", "size": "Small", "origin": "Scotland", "lifespan": "13–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Toto from The Wizard of Oz was a Cairn Terrier — though the book describes Toto as a small black dog. Toto's real name was Terry and she earned $125 a week."},
    {"name": "Australian Terrier", "description": "Australia's first native breed, the Australian Terrier was bred to control rats and snakes in the rough Australian outback. They are spirited but not aggressive.", "temperament": "Spirited, Alert, Loyal, Loveable", "size": "Small", "origin": "Australia", "lifespan": "11–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Australian Terriers were the first native-bred Australian dog to be officially recognized by the Australian Kennel Control and the first to be shown in England."},
    {"name": "Dandie Dinmont", "description": "Named after a character in a Walter Scott novel, the Dandie Dinmont is a unique terrier with a distinctive topknot of hair and a long, low body.", "temperament": "Independent, Intelligent, Determined, Reserved", "size": "Small", "origin": "Scotland", "lifespan": "12–15 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "The Dandie Dinmont is the only breed named after a fictional character — a farmer in Walter Scott's 1815 novel 'Guy Mannering.'"},
    {"name": "Boston Bull", "description": "The 'American Gentleman' in a tuxedo coat, the Boston Terrier is lively, intelligent, and uniquely American — the first non-sporting breed developed in the US.", "temperament": "Friendly, Lively, Alert, Gentle", "size": "Small", "origin": "United States", "lifespan": "11–13 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "The Boston Terrier was the first breed developed in the United States and is the official state dog of Massachusetts. They were originally much larger fighting dogs."},
    {"name": "Miniature Schnauzer", "description": "Spirited and obedient, Miniature Schnauzers are the most popular of the three schnauzer sizes. Their distinctive beard and eyebrows make them instantly recognizable.", "temperament": "Friendly, Smart, Obedient, Alert", "size": "Small", "origin": "Germany", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Miniature Schnauzers were created by crossing Standard Schnauzers with Affenpinschers and Poodles. They were originally farm ratters in Germany."},
    {"name": "Giant Schnauzer", "description": "The largest of the three schnauzer types, the Giant Schnauzer is a powerful working dog bred in Bavaria to drive cattle and guard breweries.", "temperament": "Loyal, Intelligent, Powerful, Dominant", "size": "Large", "origin": "Germany", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Giant Schnauzers were used as police and military dogs in Germany in both World Wars. They are still widely used in European police forces today."},
    {"name": "Standard Schnauzer", "description": "The original schnauzer, the Standard has been a German farm dog and ratter for centuries. They are robust, spirited, and highly trainable.", "temperament": "Lively, Intelligent, Good-Natured, Playful", "size": "Medium", "origin": "Germany", "lifespan": "13–16 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Standard Schnauzers appear in paintings by Rembrandt and Dürer from the 1400s and 1500s, making them one of the oldest verifiably depicted dog breeds."},
    {"name": "Scotch Terrier", "description": "Dignified and independent, the Scottish Terrier is one of the most recognizable breeds. They are feisty, loyal, and famously stubborn.", "temperament": "Feisty, Courageous, Independent, Loyal", "size": "Small", "origin": "Scotland", "lifespan": "11–13 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "Scottish Terriers have been owned by more US presidents than any other breed including FDR (Fala), Eisenhower, and George W. Bush. They are also a Monopoly piece."},
    {"name": "Tibetan Terrier", "description": "Despite the name, the Tibetan Terrier is not a true terrier. They were bred by Tibetan monks and considered lucky charms, never sold — only given as gifts.", "temperament": "Gentle, Sensitive, Loyal, Amiable", "size": "Medium", "origin": "Tibet", "lifespan": "15–16 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "Tibetan Terriers have large, flat, round feet — like snowshoes — perfectly evolved for navigating Himalayan terrain and deep snow."},
    {"name": "Silky Terrier", "description": "The Australian Silky Terrier combines the true terrier spirit with the glamour of a long, silky coat. They are inquisitive, alert, and affectionate.", "temperament": "Alert, Inquisitive, Friendly, Quick", "size": "Small", "origin": "Australia", "lifespan": "13–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Silky Terriers were created by crossing Yorkshire Terriers with Australian Terriers in the 1800s. Despite their delicate appearance, they are enthusiastic rat hunters."},
    {"name": "Soft-Coated Wheaten Terrier", "description": "The Wheaten is happy, steady, and full of confidence. Their soft, silky wheat-coloured coat doesn't shed — unusual for a terrier.", "temperament": "Playful, Energetic, Happy, Devoted", "size": "Medium", "origin": "Ireland", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Wheaten Terriers greet guests with an enthusiastic jump called 'the Wheaten greeting' — a characteristic so common it has its own name."},
    {"name": "West Highland White Terrier", "description": "Cheerful and self-assured, the Westie is always happy and full of self-esteem. Their pure white coat and bright dark eyes are irresistible.", "temperament": "Cheerful, Confident, Entertaining, Loyal", "size": "Small", "origin": "Scotland", "lifespan": "13–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Westies are white by design — Colonel Edward Donald Malcolm bred out all other colours after accidentally shooting his favourite dark-coated terrier during a hunt."},
    {"name": "Lhasa", "description": "An ancient sentinel dog from the Himalayan monasteries of Tibet, the Lhasa Apso was bred to alert monks to intruders with a distinctive bark.", "temperament": "Confident, Smart, Comical, Assertive", "size": "Small", "origin": "Tibet", "lifespan": "12–15 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "Lhasa Apsos were believed to be the reincarnation of monks who had not yet achieved Nirvana. The Dalai Lama traditionally gave them as sacred gifts to visiting dignitaries."},

    # ── Retrievers / Sporting ─────────────────────────────────────────────────
    {"name": "Flat-Coated Retriever", "description": "Often called the 'Peter Pan' of retrievers, the Flat-Coat maintains a puppy-like enthusiasm throughout its life. Exuberant, optimistic, and people-oriented.", "temperament": "Exuberant, Good-Natured, Optimistic, Active", "size": "Large", "origin": "England", "lifespan": "8–10 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "The Flat-Coated Retriever was the most popular retriever breed in England before the Labrador and Golden surpassed them in popularity."},
    {"name": "Curly-Coated Retriever", "description": "The oldest of the retriever breeds, the Curly-Coat has a distinctive tight curl over its entire body. They are confident, independent, and excellent swimmers.", "temperament": "Confident, Independent, Intelligent, Proud", "size": "Large", "origin": "England", "lifespan": "9–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "The Curly-Coated Retriever is the tallest of the retriever breeds. Their tight curls are water-resistant — perfect for retrieving from cold water and dense brush."},
    {"name": "Golden Retriever", "description": "One of the most popular family dogs worldwide, Golden Retrievers are known for their friendly nature, intelligence, and unwavering loyalty.", "temperament": "Intelligent, Friendly, Reliable, Trustworthy", "size": "Large", "origin": "Scotland", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Golden Retrievers have such a gentle bite they can carry a raw egg in their mouth without cracking it."},
    {"name": "Labrador Retriever", "description": "Outgoing and eager to please, Labradors are the world's most popular breed and excel as guide dogs, search-and-rescue workers, and family companions.", "temperament": "Gentle, Intelligent, Outgoing, Trusting", "size": "Large", "origin": "Canada", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Labradors were the most popular dog breed in the United States for over 30 consecutive years."},
    {"name": "Chesapeake Bay Retriever", "description": "Bred to retrieve waterfowl from the icy waters of Chesapeake Bay, the Chessie is the toughest of all retrievers with a distinctive oily, wavy coat.", "temperament": "Affectionate, Intelligent, Bright, Sensitive", "size": "Large", "origin": "United States", "lifespan": "10–13 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "The Chesapeake Bay Retriever's oily coat repels water like a duck's feathers, allowing them to work in icy water for hours without becoming waterlogged."},
    {"name": "German Short-Haired Pointer", "description": "The ultimate versatile hunting dog, the German Shorthaired Pointer can point, retrieve, and trail on land or water. Athletic, intelligent, and enthusiastic.", "temperament": "Friendly, Smart, Willing, Enthusiastic", "size": "Large", "origin": "Germany", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "German Shorthaired Pointers are so energetic they require at least 2 hours of vigorous exercise daily. They have webbed feet for swimming."},
    {"name": "Vizsla", "description": "Gentle and lively, Vizslas are Hungarian hunting dogs that form an almost inseparable bond with their owners. They are nicknamed 'Velcro dogs.'", "temperament": "Gentle, Loyal, Affectionate, Energetic", "size": "Medium", "origin": "Hungary", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Vizslas are one of only a few breeds that can be both a pointer and a retriever. Their golden-rust coat exactly matches autumn leaves."},
    {"name": "English Setter", "description": "Elegant and gentle, the English Setter is a beautifully marked bird dog that 'sets' — crouches low — when it locates prey. One of the oldest sporting breeds.", "temperament": "Gentle, Friendly, Mellow, People-Oriented", "size": "Large", "origin": "England", "lifespan": "12 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "English Setters originally lay completely flat — 'set' — when they located birds, allowing hunters to throw nets over both dog and birds."},
    {"name": "Irish Setter", "description": "Rollicking and exuberant, Irish Setters are known for their rich mahogany coat and outgoing personality. They are one of the most beautiful sporting breeds.", "temperament": "Energetic, Fun-Loving, Affectionate, Active", "size": "Large", "origin": "Ireland", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "An Irish Setter named King Timahoe lived in the White House during Nixon's presidency. The breed took off in popularity after the film 'Big Red' in 1962."},
    {"name": "Gordon Setter", "description": "The heaviest and most powerful of the setters, the Gordon was developed in Scotland by the Duke of Gordon. They are loyal, alert, and capable bird dogs.", "temperament": "Loyal, Confident, Alert, Bold", "size": "Large", "origin": "Scotland", "lifespan": "12–13 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Gordon Setters are the only setter that is entirely black and tan. They were developed to hunt on rugged Scottish moors and have superior cold-weather endurance."},
    {"name": "Brittany Spaniel", "description": "Athletic and energetic, the Brittany is a French bird dog that is smaller and faster than most setters. Despite the name, they behave more like a setter.", "temperament": "Agile, Adaptable, Bright, Fun-Loving", "size": "Medium", "origin": "France", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Brittany Spaniels were recently renamed simply 'Brittany' by the American Kennel Club because they point like setters, not flush like spaniels."},
    {"name": "Clumber", "description": "The heaviest of all spaniels, the Clumber is a slow but deliberate hunter developed in England. They are gentle, calm, and loveable couch dogs at home.", "temperament": "Gentle, Loyal, Dignified, Clownish", "size": "Large", "origin": "England", "lifespan": "10–12 years", "energy_level": "Low", "shedding": "Heavy", "fun_fact": "Clumber Spaniels were a favourite of British royalty — Prince Albert and King Edward VII were enthusiastic breeders. They nearly went extinct after WWI."},
    {"name": "English Springer", "description": "The oldest of the land spaniels, the English Springer is an enthusiastic flusher and retriever with a friendly, outgoing personality. Excellent with families.", "temperament": "Friendly, Playful, Obedient, Active", "size": "Medium", "origin": "England", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "English Springer Spaniels are so fast in the field that the breed's name comes from their ability to 'spring' or flush game birds from hiding."},
    {"name": "Welsh Springer Spaniel", "description": "Distinct from the English Springer, the Welsh Springer has an exclusively red-and-white coat and has been bred in Wales for centuries. Loyal and affectionate.", "temperament": "Loyal, Affectionate, Active, Gentle", "size": "Medium", "origin": "Wales", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Welsh Springer Spaniels appear in tapestries dating to 1570, making them one of the oldest spaniel breeds with documentary proof."},
    {"name": "Cocker Spaniel", "description": "Merry and gentle, Cocker Spaniels are one of the most beloved spaniel breeds. Their expressive eyes and silky ears make them instantly recognizable.", "temperament": "Gentle, Smart, Happy, Trusting", "size": "Medium", "origin": "England", "lifespan": "10–14 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "The Cocker Spaniel was the most popular breed in the US for 16 consecutive years in the 1940s–50s, fuelled by the fame of Disney's Lady and the Tramp."},
    {"name": "Sussex Spaniel", "description": "A low, long spaniel from Sussex, England, the Sussex is unusual for a spaniel — they often give tongue (bark) when trailing game, like a hound.", "temperament": "Friendly, Calm, Cheerful, Sociable", "size": "Medium", "origin": "England", "lifespan": "11–13 years", "energy_level": "Low", "shedding": "Medium", "fun_fact": "Sussex Spaniels nearly went extinct after WWII — only eight dogs survived. The breed was saved by one dedicated breeder, Joy Freer."},
    {"name": "Irish Water Spaniel", "description": "The tallest of all spaniels, the Irish Water Spaniel has a distinctive poodle-like curly coat and a rat tail. They are clownish and enthusiastic swimmers.", "temperament": "Playful, Inquisitive, Hardworking, Alert", "size": "Large", "origin": "Ireland", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Low", "fun_fact": "The Irish Water Spaniel has a naturally water-resistant double coat and webbed feet, making them exceptional waterfowl retrievers in any weather."},

    # ── Herding ───────────────────────────────────────────────────────────────
    {"name": "Kuvasz", "description": "An ancient Hungarian livestock guardian, the Kuvasz has protected flocks from wolves and bears for over a thousand years. They are devoted to family but wary of strangers.", "temperament": "Loyal, Patient, Protective, Polite", "size": "Large", "origin": "Hungary", "lifespan": "10–12 years", "energy_level": "Medium", "shedding": "Heavy", "fun_fact": "King Matthias I of Hungary loved Kuvaszok so much he declared them a royal symbol. He reportedly trusted his dogs more than his human guards."},
    {"name": "Schipperke", "description": "A small but spunky Belgian barge dog, the Schipperke was used to guard canal boats and hunt rats. They are mischievous, curious, and full of energy.", "temperament": "Curious, Energetic, Mischievous, Confident", "size": "Small", "origin": "Belgium", "lifespan": "13–15 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Schipperke means 'little captain' in Flemish — they were the guard dogs of Belgian canal boat captains. Queen Marie Henriette started a craze for them in 1885."},
    {"name": "Groenendael", "description": "The black Belgian Shepherd variety, the Groenendael is a hardworking herding dog used worldwide as a police and military working dog.", "temperament": "Intelligent, Energetic, Alert, Protective", "size": "Large", "origin": "Belgium", "lifespan": "10–14 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Belgian Shepherds served in both World Wars, carrying messages, pulling ambulance carts, and serving as Red Cross dogs on the front lines."},
    {"name": "Malinois", "description": "The Belgian Malinois is the world's premier police and military working dog. Intense, driven, and athletic, they require an experienced owner.", "temperament": "Confident, Hardworking, Active, Protective", "size": "Large", "origin": "Belgium", "lifespan": "14–16 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "A Malinois named Cairo participated in the Navy SEAL raid that killed Osama bin Laden in 2011. They are now used in nearly all elite special forces units."},
    {"name": "Briard", "description": "An ancient French herding dog, the Briard has a distinctive wavy double coat and a 'beard.' They served as messenger and medical supply dogs in WWI.", "temperament": "Loyal, Intelligent, Faithful, Obedient", "size": "Large", "origin": "France", "lifespan": "12 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Thomas Jefferson brought Briards to America in 1789 after admiring them in France. Lafayette also sent Jefferson a pair after the French Revolution."},
    {"name": "Kelpie", "description": "The Australian Kelpie is one of the world's most efficient herding dogs, capable of mustering thousands of sheep across vast distances with minimal direction.", "temperament": "Alert, Energetic, Loyal, Intelligent", "size": "Medium", "origin": "Australia", "lifespan": "10–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Kelpies can muster 3,000+ sheep alone. They run across the backs of sheep in a packed mob to reach the other side — a technique called 'back-running.'"},
    {"name": "Komondor", "description": "The Komondor's iconic corded white coat can reach the ground and weigh up to 15 kg. This Hungarian livestock guardian camouflages among sheep it protects.", "temperament": "Loyal, Brave, Steady, Calm", "size": "Large", "origin": "Hungary", "lifespan": "10–12 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "A Komondor's cords protect them from wolf bites — the thick ropes of hair are nearly impenetrable. Their coat can take two full days to dry after bathing."},
    {"name": "Old English Sheepdog", "description": "Boisterous and bear-like, the Old English Sheepdog was bred to drive cattle and sheep to market. Their shuffling gait is unique among dog breeds.", "temperament": "Adaptable, Gentle, Intelligent, Comical", "size": "Large", "origin": "England", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Old English Sheepdogs originally had their tails docked to identify them as working dogs and exempt their owners from taxes — giving rise to the nickname 'Bobtail.'"},
    {"name": "Shetland Sheepdog", "description": "Responsive and energetic, Shelties are miniature working collies from the Shetland Islands. They excel at agility and obedience and are devoted to their families.", "temperament": "Playful, Energetic, Responsive, Alert", "size": "Small", "origin": "Scotland", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Despite their small size, Shelties regularly beat larger breeds in agility and obedience competitions thanks to their extraordinary intelligence and trainability."},
    {"name": "Collie", "description": "Graceful and loyal, Collies are famous for their devotion and intelligence. Lassie, the most famous fictional dog, is a Rough Collie.", "temperament": "Graceful, Devoted, Responsive, Intelligent", "size": "Large", "origin": "Scotland", "lifespan": "12–14 years", "energy_level": "Medium", "shedding": "Heavy", "fun_fact": "Lassie Come Home (1943) launched the Rough Collie to global fame. All Lassies were played by male Collies despite Lassie being written as female."},
    {"name": "Border Collie", "description": "Widely considered the world's most intelligent dog, Border Collies have an extraordinary ability to learn commands and an almost psychic herding instinct.", "temperament": "Intelligent, Energetic, Alert, Tenacious", "size": "Medium", "origin": "Scotland / England", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "A Border Collie named Chaser learned the names of over 1,000 individual objects — the largest tested vocabulary of any non-human animal."},
    {"name": "Bouvier Des Flandres", "description": "A powerful Belgian farm dog used for cattle driving, cart pulling, and general farm work. Now a premier police and protection dog worldwide.", "temperament": "Loyal, Intelligent, Steady, Protective", "size": "Large", "origin": "Belgium", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Bouviers des Flandres served in WWI as ambulance dogs and message carriers. They nearly went extinct — the breed was rebuilt from only a handful of survivors."},
    {"name": "Rottweiler", "description": "Robust and powerful, Rottweilers are devoted guardians with a calm confidence. Properly trained, they are loving family dogs.", "temperament": "Loyal, Loving, Confident, Alert", "size": "Large", "origin": "Germany", "lifespan": "9–10 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Rottweilers descend from Roman drover dogs used to herd livestock and pull carts for butchers in Rottweil, Germany."},
    {"name": "German Shepherd", "description": "Confident and courageous, German Shepherds are the world's leading police and military dog and one of the most loyal family protectors.", "temperament": "Loyal, Confident, Courageous, Intelligent", "size": "Large", "origin": "Germany", "lifespan": "9–13 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "German Shepherds were the first dogs trained as guide dogs for the visually impaired, in post-WWI Germany."},

    # ── Working / Guard ───────────────────────────────────────────────────────
    {"name": "Doberman", "description": "Intelligent and fearless, Dobermans are among the most capable protection dogs in the world. With proper socialisation, they are affectionate family companions.", "temperament": "Loyal, Fearless, Alert, Intelligent", "size": "Large", "origin": "Germany", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Low", "fun_fact": "The Doberman was created by a German tax collector named Karl Friedrich Louis Dobermann, who wanted a loyal protection dog for his rounds."},
    {"name": "Miniature Pinscher", "description": "The 'King of Toys,' the Miniature Pinscher is a fearless, energetic little dog that looks like a miniature Doberman but is actually an older, separate breed.", "temperament": "Fearless, Energetic, Alert, Proud", "size": "Small", "origin": "Germany", "lifespan": "12–16 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Despite their resemblance, Miniature Pinschers are not miniature Dobermans. They predate the Doberman and were bred from the German Pinscher, Dachshund, and Italian Greyhound."},
    {"name": "Greater Swiss Mountain Dog", "description": "The largest of the four Swiss mountain dog breeds, the Swissy is a powerful draft dog with a gentle, devoted temperament. They pulled carts for Swiss farmers.", "temperament": "Friendly, Devoted, Gentle, Alert", "size": "Giant", "origin": "Switzerland", "lifespan": "8–11 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "Greater Swiss Mountain Dogs nearly went extinct and were 'rediscovered' by Swiss dog researchers in 1908. Today they still have relatively small populations."},
    {"name": "Bernese Mountain Dog", "description": "Calm and affectionate, Bernese Mountain Dogs are gentle giants bred to pull carts and drive cattle in the Swiss Alps. They are devoted family dogs.", "temperament": "Calm, Affectionate, Loyal, Faithful", "size": "Large", "origin": "Switzerland", "lifespan": "7–10 years", "energy_level": "Medium", "shedding": "Heavy", "fun_fact": "Bernese Mountain Dogs are one of four Swiss mountain dog breeds and were nearly extinct by the early 1900s before enthusiasts revived them."},
    {"name": "Appenzeller", "description": "The rarest of the four Swiss mountain dog breeds, the Appenzeller is a lively, versatile farm dog used for herding, guarding, and draft work.", "temperament": "Lively, Self-Assured, Reliable, Energetic", "size": "Medium", "origin": "Switzerland", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Medium", "fun_fact": "Appenzeller Mountain Dogs are almost exclusively found in Switzerland and are rarely seen outside their native country. They have a distinctive, musical bark."},
    {"name": "Entlebucher", "description": "The smallest of the Swiss mountain dog breeds, the Entlebucher is an energetic herder with a short, glossy tricolour coat and natural bobtail.", "temperament": "Loyal, Lively, Intelligent, Determined", "size": "Medium", "origin": "Switzerland", "lifespan": "11–13 years", "energy_level": "High", "shedding": "Low", "fun_fact": "The Entlebucher's name comes from the Entlebuch valley in Switzerland. They were nearly extinct after WWII and were revived from a small group of surviving dogs."},
    {"name": "Boxer", "description": "Energetic and playful, Boxers are patient and protective with children. They remain puppy-like in spirit well into adulthood.", "temperament": "Playful, Energetic, Loyal, Bright", "size": "Large", "origin": "Germany", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Boxers got their name from their habit of standing on their hind legs and 'boxing' with their front paws during play."},
    {"name": "Bull Mastiff", "description": "Bred in 19th-century England to guard estates against poachers, the Bullmastiff is a powerful, confident guardian that is gentle and affectionate with family.", "temperament": "Reliable, Loyal, Devoted, Alert", "size": "Large", "origin": "England", "lifespan": "7–9 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "Bullmastiffs were bred to be 60% Mastiff and 40% Bulldog — the Mastiff's size and the Bulldog's ferocity. They were called 'The Gamekeeper's Night Dog.'"},
    {"name": "Tibetan Mastiff", "description": "One of the most ancient and powerful breeds, the Tibetan Mastiff guarded Himalayan monasteries and villages. They are independent, protective, and imposing.", "temperament": "Independent, Reserved, Loyal, Protective", "size": "Giant", "origin": "Tibet", "lifespan": "10–12 years", "energy_level": "Low", "shedding": "Heavy", "fun_fact": "A single Tibetan Mastiff puppy sold for $2 million in China in 2014 — making it the most expensive dog ever sold. They were once traded along the Silk Road."},
    {"name": "French Bulldog", "description": "Playful and low-energy, French Bulldogs are ideal city dogs known for their bat-like ears, affectionate personalities, and quiet nature.", "temperament": "Playful, Affectionate, Easygoing, Sociable", "size": "Small", "origin": "France", "lifespan": "10–12 years", "energy_level": "Low", "shedding": "Low", "fun_fact": "French Bulldogs can't swim due to their heavy front bodies and short legs. Always supervise them near water."},
    {"name": "Great Dane", "description": "Majestic and friendly, Great Danes are known as the 'Apollo of Dogs.' Despite their enormous size, they are gentle and patient.", "temperament": "Friendly, Patient, Dependable, Gentle", "size": "Giant", "origin": "Germany", "lifespan": "7–10 years", "energy_level": "Medium", "shedding": "Medium", "fun_fact": "Zeus, a Great Dane, held the Guinness World Record for tallest dog at 111.8 cm tall — taller than most kitchen counters."},
    {"name": "Saint Bernard", "description": "Gentle and patient, Saint Bernards are legendary rescue dogs of the Swiss Alps. Despite their massive size, they are calm and great with children.", "temperament": "Gentle, Patient, Friendly, Watchful", "size": "Giant", "origin": "Switzerland", "lifespan": "8–10 years", "energy_level": "Medium", "shedding": "Heavy", "fun_fact": "Saint Bernards are famous for Alpine rescues, but the iconic barrel of brandy around their neck is a myth — invented by a painter in 1820."},
    {"name": "Eskimo Dog", "description": "The Canadian Eskimo Dog is one of North America's oldest and rarest indigenous breeds, used by the Inuit for sled pulling and hunting polar bears.", "temperament": "Tough, Loyal, Brave, Affectionate", "size": "Large", "origin": "Canada / Arctic", "lifespan": "10–15 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Canadian Eskimo Dogs nearly went extinct — there were fewer than 200 left by the 1970s. The Canadian government systematically culled Inuit sled dogs in the 1950s–60s."},
    {"name": "Malamute", "description": "Powerful and sturdy, Alaskan Malamutes are one of the oldest Arctic sled dog breeds, built for hauling heavy freight over long distances.", "temperament": "Affectionate, Loyal, Playful, Dignified", "size": "Large", "origin": "Alaska, USA", "lifespan": "10–14 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Malamutes are often confused with Huskies but are much larger and were bred for strength rather than speed. They can pull loads over twice their body weight."},
    {"name": "Siberian Husky", "description": "Athletic and outgoing, Siberian Huskies were bred by the Chukchi people of Siberia for long-distance sled pulling in extreme cold.", "temperament": "Outgoing, Alert, Gentle, Friendly", "size": "Medium", "origin": "Siberia, Russia", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "In 1925, a relay of Siberian Huskies delivered life-saving diphtheria serum 1,000 km across Alaska to Nome — the inspiration for the Iditarod race."},
    {"name": "Affenpinscher", "description": "Nicknamed the 'Monkey Terrier' for their primate-like expression, Affenpinschers are bold, curious, and utterly fearless despite their tiny size.", "temperament": "Bold, Curious, Entertaining, Stubborn", "size": "Small", "origin": "Germany", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Affenpinscher means 'monkey-like terrier' in German. They are one of the oldest toy breeds and appear in 17th-century paintings by Jan Steen."},
    {"name": "Basenji", "description": "The 'barkless dog' from Central Africa, the Basenji communicates with yodels, howls, and whines. They are catlike in their fastidiousness.", "temperament": "Alert, Energetic, Curious, Affectionate", "size": "Small", "origin": "Congo", "lifespan": "13–14 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Basenjis can't bark because of the shape of their larynx, but they make a distinctive yodel called a 'baroo.' They are also one of the oldest breeds — appearing in ancient Egyptian art."},
    {"name": "Pug", "description": "Charming and mischievous, Pugs have been companion dogs to emperors and royalty for centuries. They love company and suffer in isolation.", "temperament": "Charming, Mischievous, Loving, Stubborn", "size": "Small", "origin": "China", "lifespan": "13–15 years", "energy_level": "Low", "shedding": "Heavy", "fun_fact": "A group of Pugs is called a 'grumble.' Pugs were treasured by Chinese emperors and guarded by soldiers."},
    {"name": "Leonberg", "description": "Majestic and gentle, Leonbergers were bred to resemble the lion on the town crest of Leonberg, Germany. They are calm family dogs despite their lion-like appearance.", "temperament": "Gentle, Friendly, Obedient, Fearless", "size": "Giant", "origin": "Germany", "lifespan": "8–9 years", "energy_level": "Medium", "shedding": "Heavy", "fun_fact": "Leonbergers were nearly wiped out in both World Wars. The breed had to be completely rebuilt from just eight surviving dogs after WWI."},
    {"name": "Newfoundland", "description": "Massive and gentle, Newfoundlands are natural-born water rescue dogs with a water-resistant coat and webbed feet. They are famously patient with children.", "temperament": "Sweet, Patient, Devoted, Gentle", "size": "Giant", "origin": "Canada", "lifespan": "9–10 years", "energy_level": "Medium", "shedding": "Heavy", "fun_fact": "Newfoundlands have rescued so many people from drowning that they are called 'the lifeguard dogs.' Napoleon Bonaparte was saved by a Newfoundland after falling overboard."},
    {"name": "Great Pyrenees", "description": "Majestic and serene, the Great Pyrenees has guarded flocks in the Pyrenean mountains for thousands of years. They are calm, patient, and devoted protectors.", "temperament": "Patient, Calm, Strong-Willed, Affectionate", "size": "Giant", "origin": "France / Spain", "lifespan": "10–12 years", "energy_level": "Low", "shedding": "Heavy", "fun_fact": "Great Pyrenees are double-dewclawed on their hind feet — this extra toe gives them grip on rocky mountain terrain. They are nocturnal guardians by nature."},
    {"name": "Samoyed", "description": "Gentle and adaptable, Samoyeds were bred by Siberian nomads to herd reindeer and sleep with their owners for warmth. Their 'Sammy smile' is unmistakable.", "temperament": "Friendly, Gentle, Adaptable, Alert", "size": "Large", "origin": "Siberia, Russia", "lifespan": "12–14 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Samoyed fur has been spun into yarn and knitted into warm garments — it is naturally hypoallergenic and odour-free."},
    {"name": "Pomeranian", "description": "Vivacious and curious, Pomeranians are tiny spitz dogs with outsized personalities. They are bold, inquisitive, and form strong bonds with their owners.", "temperament": "Bold, Curious, Vivacious, Sociable", "size": "Small", "origin": "Poland / Germany", "lifespan": "12–16 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Two Pomeranians were among only three dogs to survive the sinking of the Titanic, carried off in lifeboats by their owners."},
    {"name": "Chow", "description": "Dignified and aloof, Chow Chows are one of the oldest and most unique breeds, known for their blue-black tongues and lion-like manes.", "temperament": "Loyal, Quiet, Independent, Serious", "size": "Medium", "origin": "China", "lifespan": "8–12 years", "energy_level": "Low", "shedding": "Heavy", "fun_fact": "Chow Chows have blue-black tongues and are one of only two dog breeds with this trait (the other is the Shar-Pei). No one is certain why."},
    {"name": "Keeshond", "description": "Friendly and outgoing, Keeshonds were the most popular companion dogs in 18th-century Holland. Their distinctive spectacle markings around the eyes are unique.", "temperament": "Outgoing, Sturdy, Lively, Alert", "size": "Medium", "origin": "Netherlands", "lifespan": "12–15 years", "energy_level": "Medium", "shedding": "Heavy", "fun_fact": "Keeshonds were the symbol of the Dutch Patriot political party in the 1780s. Their name comes from the party's leader, Kees de Gyselaer."},
    {"name": "Brabancon Griffon", "description": "The Brussels Griffon (smooth-coated variety) is a small but self-important toy dog with an almost human-like face. Alert and sensitive.", "temperament": "Alert, Sensitive, Curious, Self-Important", "size": "Small", "origin": "Belgium", "lifespan": "12–15 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "The Brussels Griffon's face allegedly inspired the Ewoks in Star Wars. Queen Astrid of Belgium popularized the breed in the early 1900s."},
    {"name": "Pembroke", "description": "Bold and active, Pembroke Welsh Corgis are Queen Elizabeth II's favourite breed. Despite their short legs, they are remarkably fast and athletic.", "temperament": "Bold, Tenacious, Friendly, Playful", "size": "Small", "origin": "Wales", "lifespan": "12–13 years", "energy_level": "High", "shedding": "Heavy", "fun_fact": "Queen Elizabeth II owned more than 30 Corgis during her reign. According to Welsh legend, Corgis were the preferred mount of fairy warriors."},
    {"name": "Cardigan", "description": "The older of the two Welsh Corgi breeds, the Cardigan has a long tail and can come in more coat colours. They are slightly more reserved than the Pembroke.", "temperament": "Loyal, Affectionate, Alert, Companionable", "size": "Small", "origin": "Wales", "lifespan": "12–15 years", "energy_level": "Medium", "shedding": "Heavy", "fun_fact": "Cardigan Welsh Corgis are over 3,000 years old — one of the oldest herding breeds in Britain. They were brought to Wales by Celtic tribes from central Europe."},
    {"name": "Toy Poodle", "description": "The smallest poodle variety, the Toy Poodle combines the breed's legendary intelligence with a compact size perfect for city living. Sharp, eager, and deeply loyal.", "temperament": "Intelligent, Active, Alert, Faithful", "size": "Small", "origin": "Germany / France", "lifespan": "10–18 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Poodles consistently rank as the second-most intelligent dog breed. Despite the fancy show clips, they were originally bred as water retrievers in Germany."},
    {"name": "Miniature Poodle", "description": "The middle-sized poodle variety is highly trainable and makes an excellent companion. Athletic enough for sport but manageable for family life.", "temperament": "Intelligent, Active, Graceful, Faithful", "size": "Small", "origin": "Germany / France", "lifespan": "10–18 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Miniature Poodles were popular circus performers in the 18th century due to their trainability and love of showing off."},
    {"name": "Standard Poodle", "description": "The original and largest poodle, the Standard was a prized waterfowl retriever. Highly intelligent, athletic, and elegant in the show ring.", "temperament": "Intelligent, Active, Dignified, Faithful", "size": "Medium", "origin": "Germany / France", "lifespan": "12–15 years", "energy_level": "High", "shedding": "Low", "fun_fact": "The elaborate show clips seen on poodles were originally functional — hunters clipped poodles to help them swim faster while leaving hair on joints for warmth."},
    {"name": "Mexican Hairless", "description": "The Xoloitzcuintli (show-low-eats-QUEENT-lee) is one of the world's oldest and rarest breeds. Revered by the Aztecs as a sacred healer and guide to the afterlife.", "temperament": "Alert, Calm, Attentive, Loyal", "size": "Medium", "origin": "Mexico", "lifespan": "13–18 years", "energy_level": "Medium", "shedding": "Low", "fun_fact": "The Xoloitzcuintli is the national dog of Mexico. They were believed by the Aztecs to guide the souls of the dead through the underworld — often sacrificed and buried with their owners."},

    # ── Wild / canids included in Stanford Dogs ────────────────────────────────
    {"name": "Dingo", "description": "The Dingo is Australia's wild dog — descended from semi-domesticated dogs brought to Australia around 3,500–4,000 years ago. They are shy but intelligent.", "temperament": "Independent, Alert, Curious, Shy", "size": "Medium", "origin": "Australia", "lifespan": "5–10 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Dingoes rarely bark — they howl, whimper, and growl to communicate. They are the largest land predator native to Australia."},
    {"name": "Dhole", "description": "The Dhole (Asian Wild Dog) is a highly social pack hunter from South and Southeast Asia. They communicate with whistles and are fierce cooperative hunters.", "temperament": "Social, Alert, Intelligent, Energetic", "size": "Medium", "origin": "South / Southeast Asia", "lifespan": "10 years", "energy_level": "High", "shedding": "Low", "fun_fact": "Dholes are endangered with fewer than 2,500 individuals remaining. They hunt in packs and can bring down prey many times their size, including tigers."},
    {"name": "African Hunting Dog", "description": "The African Wild Dog (Painted Wolf) is one of the most efficient hunters in Africa, with an 80% hunt success rate — far above lions (25%) and leopards (38%).", "temperament": "Social, Intelligent, Alert, Energetic", "size": "Medium", "origin": "Sub-Saharan Africa", "lifespan": "10–12 years", "energy_level": "High", "shedding": "Low", "fun_fact": "African Wild Dogs are critically endangered with fewer than 6,000 remaining. Each dog has a unique coat pattern — no two are alike, like human fingerprints."},

]


def seed_breeds(db: Session) -> None:
    """Clear and re-seed if breed count doesn't match the full 120."""
    if db.query(BreedMetadata).count() == len(_BREEDS):
        return
    db.query(BreedMetadata).delete()
    for data in _BREEDS:
        db.add(BreedMetadata(**data))
    db.commit()
    print(f"[iDogtify] Seeded {len(_BREEDS)} breeds into database.")
